import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Roboto } from 'next/font/google'
import Header from '@/components/Header'
import "./globals.css";


const roboto = Roboto({ subsets: ['latin'], weight: ['400','700'], variable: '--font-body' })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={roboto.variable}>
      <body>
         <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-sky-50">
        <Header/>
        {children} 
        </div>
    </body>
    </html>
  )
}
